# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0002_auto_20180513_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='nid',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Parent Entity Name'),
        ),
    ]
