# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0004_auto_20180513_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityfile',
            name='filename',
            field=models.CharField(max_length=60),
        ),
    ]
