# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0005_auto_20180513_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='final',
            field=models.TextField(blank=True, null=True, verbose_name='Final Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='google',
            field=models.TextField(blank=True, null=True, verbose_name='Google Translated Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='original',
            field=models.TextField(blank=True, null=True, verbose_name='Original Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='papago',
            field=models.TextField(blank=True, null=True, verbose_name='Papago Translated Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='reference',
            field=models.TextField(blank=True, null=True, verbose_name='Reference Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='translate',
            field=models.TextField(blank=True, null=True, verbose_name='Translated Text(JSON)'),
        ),
    ]
