# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0010_auto_20180518_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': '번역 대상', 'verbose_name_plural': '번역 대상 목록'},
        ),
        migrations.AlterModelOptions(
            name='entityfile',
            options={'verbose_name': '대상 파일', 'verbose_name_plural': '대상 파일 목록'},
        ),
        migrations.AlterModelOptions(
            name='noun',
            options={'verbose_name': '명사', 'verbose_name_plural': '명사 목록'},
        ),
        migrations.AlterModelOptions(
            name='nouncate',
            options={'verbose_name': '명사 분류', 'verbose_name_plural': '명사 분류 목록'},
        ),
        migrations.AlterField(
            model_name='noun',
            name='final',
            field=models.CharField(max_length=50, verbose_name='최종본'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='papago',
            field=models.CharField(max_length=50, verbose_name='파파고'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='refer',
            field=models.CharField(max_length=50, verbose_name='참고의견'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='translate',
            field=models.CharField(max_length=50, verbose_name='번역'),
        ),
    ]
