# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0012_auto_20180519_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noun',
            old_name='refer',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='noun',
            name='google',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='구글'),
        ),
    ]
