# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0014_auto_20180519_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='reference',
            field=models.TextField(blank=True, default='', null=True, verbose_name='참고의견'),
        ),
    ]
