# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0015_auto_20180519_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='final',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Final Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='google',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={},
                                                                 verbose_name='Google Translated Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='original',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Original Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='papago',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={},
                                                                 verbose_name='Papago Translated Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='reference',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Reference Text(JSON)'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='translate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Translated Text(JSON)'),
        ),
    ]
