# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 05:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunless_web', '0016_auto_20180520_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='checker',
            field=models.ManyToManyField(related_name='검수자', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entity',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities',
                                    to='sunless_web.EntityFile', verbose_name='소속 파일'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='key',
            field=models.IntegerField(db_index=True, verbose_name='파일상 ID'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='parent',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='부모 항목'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
