# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0017_auto_20180520_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='noun_error',
            field=models.BooleanField(default=False, verbose_name='has error'),
        ),
    ]
