# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0018_entity_noun_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noun',
            options={'verbose_name': '명사', 'verbose_name_plural': '명사 사전'},
        ),
        migrations.AddField(
            model_name='nouncate',
            name='icon',
            field=models.CharField(default='fas fa-book', max_length=50, verbose_name='아이콘 클래스'),
        ),
    ]
