# Generated by Django 2.0.5 on 2018-05-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0020_auto_20180525_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityfile',
            options={'verbose_name': '번역 파일', 'verbose_name_plural': '번역 파일 목록'},
        ),
        migrations.RemoveField(
            model_name='entityfile',
            name='id',
        ),
        migrations.AlterField(
            model_name='entityfile',
            name='filename',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
