# Generated by Django 2.0.5 on 2018-05-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0021_auto_20180526_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityFile',
            new_name='EntityCate',
        ),
        migrations.RenameField(
            model_name='entitycate',
            old_name='filename',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='file',
        ),
        migrations.AddField(
            model_name='entity',
            name='cate',
            field=models.ForeignKey(default='events', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='entities', to='sunless_web.EntityCate', verbose_name='소속 파일'),
            preserve_default=False,
        ),
    ]
