# Generated by Django 2.0.5 on 2018-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0022_auto_20180526_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='translated',
            field=models.BooleanField(default=False, verbose_name='변역 완료 여부'),
        ),
    ]
