# Generated by Django 2.0.5 on 2018-05-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0023_entity_translated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=300, verbose_name='응답')),
            ],
            options={
                'verbose_name': '응답',
                'verbose_name_plural': '응답들',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, verbose_name='패턴')),
            ],
            options={
                'verbose_name': '대화',
                'verbose_name_plural': '대화집',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                    to='sunless_web.Conversation', verbose_name='대화'),
        ),
    ]
