# Generated by Django 2.0.5 on 2018-05-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0024_auto_20180527_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chance',
            field=models.FloatField(default=0.0, verbose_name='응답확률'),
        ),
    ]
