# Generated by Django 2.0.5 on 2018-05-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0025_conversation_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='finalized',
            field=models.IntegerField(default=0, verbose_name='변역 확정 숫자'),
        ),
        migrations.AddField(
            model_name='entity',
            name='items',
            field=models.IntegerField(default=0, verbose_name='변역 항목 숫자'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='translated',
            field=models.IntegerField(default=0, verbose_name='변역 완료 숫자'),
        ),
    ]
