# Generated by Django 2.0.5 on 2018-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0026_auto_20180528_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='', verbose_name='패치파일')),
                ('translated', models.IntegerField(default=0, verbose_name='변역 완료 숫자')),
                ('finalized', models.IntegerField(default=0, verbose_name='변역 확정 숫자')),
                ('items', models.IntegerField(default=0, verbose_name='변역 항목 숫자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '패치',
                'verbose_name_plural': '패치 목록',
            },
        ),
    ]
