# Generated by Django 2.0.5 on 2018-05-28 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0027_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='noun',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noun',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
