# Generated by Django 2.0.5 on 2018-05-28 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0029_auto_20180528_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='filename',
            new_name='file',
        ),
    ]
