# Generated by Django 2.0.5 on 2018-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0032_auto_20180528_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='download',
            field=models.IntegerField(default=0, verbose_name='다운로드 수'),
        ),
    ]
