# Generated by Django 2.0.5 on 2018-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0033_patch_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='이름'),
        ),
    ]
