# Generated by Django 2.0.5 on 2018-06-02 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('sunless_web', '0034_auto_20180529_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='telegram', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram_id', models.IntegerField(verbose_name='Telegram ID')),
            ],
            options={
                'verbose_name': '텔레그램 유저',
                'verbose_name_plural': '텔레그램 유저 목록',
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='translated',
            field=models.IntegerField(default=0, verbose_name='초벌 번역 숫자'),
        ),
    ]
