# Generated by Django 2.0.5 on 2018-06-15 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0035_auto_20180602_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaEntity',
            fields=[
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역 목록',
                'proxy': True,
                'indexes': [],
            },
            bases=('sunless_web.entity',),
        ),
        migrations.CreateModel(
            name='OtherEntity',
            fields=[
            ],
            options={
                'verbose_name': '번역 대상',
                'verbose_name_plural': '번역 대상 목록',
                'proxy': True,
                'indexes': [],
            },
            bases=('sunless_web.entity',),
        ),
    ]
