# Generated by Django 2.0.5 on 2018-09-01 05:52

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunless_web', '0036_areaentity_otherentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '논의',
                'verbose_name_plural': '논의 목록',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=256, verbose_name='위치')),
                ('hash_v1', models.CharField(db_index=True, max_length=70, unique=True, verbose_name='HashHex v1')),
                ('hash_v2', models.CharField(db_index=True, max_length=70, unique=True, verbose_name='HashHex v2')),
                ('text', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Text(JSON)')),
                ('translated', models.TextField(verbose_name='번역')),
                ('status', models.CharField(choices=[('none', '안됨'), ('proto', '검수 필요'), ('discuss', '논의 필요'), ('verified', '완료')], default='none', max_length=4, verbose_name='번역 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sunless_web.EntityCate', verbose_name='소속 파일')),
                ('checker', models.ManyToManyField(related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '번역 대상',
                'verbose_name_plural': '번역 대상 목록',
            },
        ),
        migrations.AddField(
            model_name='discuss',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discusses', to='sunless_web.Entry'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discusses', to=settings.AUTH_USER_MODEL),
        ),
    ]
