# Generated by Django 2.0.5 on 2018-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0037_auto_20180901_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='hash_v2',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True, unique=True, verbose_name='HashHex v2'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='hash',
            field=models.CharField(db_index=True, max_length=70, unique=True, verbose_name='HashHex V1'),
        ),
    ]
