# Generated by Django 2.0.5 on 2018-09-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0038_auto_20180901_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='translated',
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(
                choices=[('none', '안됨'), ('proto', '검수 필요'), ('discuss', '논의 필요'), ('verified', '완료')], default='none',
                max_length=10, verbose_name='번역 상태'),
        ),
    ]
