# Generated by Django 2.0.5 on 2018-09-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0040_auto_20180901_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cate',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='sunless_web.EntityCate', verbose_name='소속 파일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='hash_v1',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True, verbose_name='HashHex v1'),
        ),
    ]
