# Generated by Django 2.0.5 on 2018-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0042_auto_20180901_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
        migrations.AddField(
            model_name='entry',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='원문'),
        ),
        migrations.AddField(
            model_name='entry',
            name='text_jr',
            field=models.TextField(blank=True, null=True, verbose_name='일어'),
        ),
        migrations.AddField(
            model_name='entry',
            name='text_jrkr',
            field=models.TextField(blank=True, null=True, verbose_name='일한번역'),
        ),
        migrations.AddField(
            model_name='entry',
            name='text_kr',
            field=models.TextField(blank=True, null=True, verbose_name='영한번역'),
        ),
    ]
