# Generated by Django 2.0.5 on 2018-09-05 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunless_web', '0044_auto_20180901_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField(default=1, verbose_name='리비전')),
                ('text', models.TextField(verbose_name='번역 제안')),
                ('discuss', models.TextField(blank=True, null=True, verbose_name='의견')),
            ],
            options={
                'verbose_name': '번역',
                'verbose_name_plural': '번역 목록',
                'ordering': ['-revision'],
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='text_kr',
        ),
        migrations.AddField(
            model_name='entry',
            name='last_revision',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='최종 리비전'),
        ),
        migrations.AddField(
            model_name='translation',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations',
                                    to='sunless_web.Entry'),
        ),
        migrations.AddField(
            model_name='translation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='translations', to=settings.AUTH_USER_MODEL),
        ),
    ]
