# Generated by Django 2.0.5 on 2018-09-18 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunless_web', '0045_auto_20180906_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='내용')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='sunless_web.Entry')),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='좋아요')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '논의',
                'verbose_name_plural': '논의 목록',
            },
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='user',
        ),
        migrations.DeleteModel(
            name='Discuss',
        ),
    ]
