# Generated by Django 2.0.5 on 2018-10-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0046_auto_20180918_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='basepath',
            field=models.CharField(default='', max_length=256, verbose_name='위치'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='path',
            field=models.CharField(default='', max_length=256, verbose_name='풀패스'),
        ),
    ]
