# Generated by Django 2.0.5 on 2018-10-04 06:47

from django.db import migrations


def forwards_func(apps, schema_editor):
    Entry = apps.get_model("sunless_web", "Entry")
    for e in Entry.objects.all():
        e.basepath = e.path[:e.path.rindex("/")]
        e.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0047_auto_20181004_1547'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
