# Generated by Django 2.0.5 on 2018-10-04 07:00

from django.db import migrations, models
import os


def forwards_func(apps, schema_editor):
    Entry = apps.get_model("sunless_web", "Entry")
    for e in Entry.objects.all():
        e.object = os.path.basename(e.path)
        e.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0048_auto_20181004_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='object',
            field=models.CharField(default='', max_length=256, verbose_name='객체명'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
