# Generated by Django 2.0.5 on 2018-10-04 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0049_entry_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='path',
        ),
    ]
