# Generated by Django 2.0.5 on 2018-10-04 11:42

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunless_web', '0052_auto_20181004_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['-created_at'], 'verbose_name': '번역', 'verbose_name_plural': '번역 목록'},
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='discuss',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='last_revision',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='revision',
        ),
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('none', '안됨'), ('proto', '검수 필요'), ('verified', '완료')], default='none',
                                   max_length=10, verbose_name='번역 상태'),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
