# Generated by Django 2.0.5 on 2018-10-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0053_auto_20181004_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text_pp',
            field=models.TextField(blank=True, null=True, verbose_name='파파고'),
        ),
    ]
