# Generated by Django 2.1.2 on 2018-10-25 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sunless_web', '0054_entry_text_pp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '토론',
                'verbose_name_plural': '토론 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='translation',
            name='msg',
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('none', '안됨'), ('need_to_discuss', '논의 필요'), ('verified', '완료')],
                                   default='none', max_length=10, verbose_name='번역 상태'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss',
                                    to='sunless_web.Entry'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='mention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discuss',
                                    to='sunless_web.Translation'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discuss',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
