# Generated by Django 2.1.2 on 2018-10-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0058_translation_ttype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='mention',
            new_name='translate',
        ),
    ]
