# Generated by Django 2.1.2 on 2018-10-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0060_auto_20181025_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='ttype',
        ),
    ]
