# Generated by Django 2.1.4 on 2019-01-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0061_remove_translation_ttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['created_at'], 'verbose_name': '토론', 'verbose_name_plural': '토론 목록'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['created_at'], 'verbose_name': '번역', 'verbose_name_plural': '번역 목록'},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.AddField(
            model_name='entrypath',
            name='status',
            field=models.CharField(choices=[('none', '안됨'), ('partial', '부분번역'), ('need_to_discuss', '논의 중'), ('verified', '완료')], default='none', max_length=10, verbose_name='번역 상태'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='translate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discusses', to='sunless_web.Translation'),
        ),
    ]
