# Generated by Django 2.1.5 on 2019-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0063_auto_20190113_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaEntity',
        ),
        migrations.DeleteModel(
            name='OtherEntity',
        ),
        migrations.AddField(
            model_name='patch',
            name='patch_type',
            field=models.CharField(choices=[('korean', '한국 번역만'), ('full', '일본 번역, 기계 번역 포함')], default='full', max_length=20, verbose_name='패치 종류'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일'),
        ),
    ]
