# Generated by Django 2.2.1 on 2020-03-14 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('sunless_web', '0065_auto_20190119_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
