# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0009_auto_20180515_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='이름')),
                ('refer', models.TextField(verbose_name='참고의견')),
                ('papago', models.TextField(verbose_name='파파고')),
                ('translate', models.TextField(verbose_name='번역')),
                ('final', models.TextField(verbose_name='최종본')),
            ],
        ),
        migrations.CreateModel(
            name='NounCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='명사 분류')),
            ],
        ),
        migrations.AddField(
            model_name='noun',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sunless_web.NounCate'),
        ),
    ]
