# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunless_web', '0011_auto_20180519_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noun',
            name='final',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='최종본'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='papago',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='파파고'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='refer',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='참고의견'),
        ),
        migrations.AlterField(
            model_name='noun',
            name='translate',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='번역'),
        ),
    ]
